### ISSUE TITLE
Revisión por pares- grupo 4

### ISSUE THREAD

**Issue by AlfaroBrenda** [martinguzol/mercadoLiebre-JoseMartinGuzmanOlivera#1]
-[ ]1-Cumple.
-[ ]2-Cumple.
-[ ]3-En 320 barra de busqueda sale fuera del fondo amarillo, en 361 "compra en cuotas" se sobrescribe  con la barra de busqueda y no es responsive.
-[ ]4-Cumple.
-[ ]5-Cumple.
-[ ]6-Cumple.
-[ ]7-Cumple.
-[ ]8-Cumple.
-[ ]9-Bien las animaciones, colores y orden de los artículos. Enlazar los formularios, y el css del home
-[ ]10-Comentar mas el código. Css de registro y login, y que sea responsive

**Comment by martinguzol** [comment]
Vista de detalles corregidas.
